apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensaola.fullname" . }}
data:
  config.yaml: |
    data_namespace: {{ .Values.config.dataNamespace | quote }}
    log:
      level: {{ .Values.config.logLevel }}
      format: {{ .Values.config.logFormat | quote }}
      file_path: {{ .Values.config.logFilePath | quote }}
    cache_cleanup_interval: {{ .Values.config.cacheCleanupInterval }}
    labels:
      component: {{ .Values.config.labels.component | quote }}
    annotations:
      component: {{ .Values.config.annotations.component | quote }}
