---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middleware.cn
  resources:
  - middlewareactionbaselines
  - middlewareactions
  - middlewarebaselines
  - middlewareconfigurations
  - middlewareoperatorbaselines
  - middlewareoperators
  - middlewarepackages
  - middlewares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middleware.cn
  resources:
  - middlewareactionbaselines/finalizers
  - middlewareactions/finalizers
  - middlewarebaselines/finalizers
  - middlewareconfigurations/finalizers
  - middlewareoperatorbaselines/finalizers
  - middlewareoperators/finalizers
  - middlewarepackages/finalizers
  - middlewares/finalizers
  verbs:
  - update
- apiGroups:
  - middleware.cn
  resources:
  - middlewareactionbaselines/status
  - middlewareactions/status
  - middlewarebaselines/status
  - middlewareconfigurations/status
  - middlewareoperatorbaselines/status
  - middlewareoperators/status
  - middlewarepackages/status
  - middlewares/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
