apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  labels:
    app.kubernetes.io/name: opensaola
    app.kubernetes.io/managed-by: kustomize
  name: middlewareactionbaseline-sample
spec:
  # TODO(user): Add fields here
