apiVersion: middleware.cn/v1
kind: MiddlewareBaseline
metadata:
  labels:
    app.kubernetes.io/name: opensaola
    app.kubernetes.io/managed-by: kustomize
  name: middlewarebaseline-sample
spec:
  # TODO(user): Add fields here
