apiVersion: v2
appVersion: "dev"
description: "A Kubernetes operator for middleware lifecycle management / 用于中间件生命周期管理的 Kubernetes 控制器"
kubeVersion: ">=1.21.0-0"
home: "https://github.com/harmonycloud/opensaola"
keywords:
- operator
- middleware
- kubernetes
maintainers:
- email: CandidXD@outlook.com
  name: CandidXD
  url: https://github.com/CandidXD
name: opensaola
sources:
- "https://github.com/harmonycloud/opensaola"
type: application
version: 0.1.3-dev.0
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: source / 源码
      url: https://github.com/harmonycloud/opensaola
